services:
  sync:
    build: .
    command: ['pytest', '--junitxml=./tests_output/pytest.xml', '--cov-report', 'xml:./tests_output/coverage.xml', '--cov=git_hg_sync', 'tests/']
    volumes:
      - ./tests_output:/app/tests_output
    environment:
      - RABBITMQ=true
    depends_on:
      pulse:
        condition: service_healthy
    networks:
      - pulse_network

  pulse:
    image: rabbitmq:3-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 2s
      retries: 1
    ports:
      - 15672:15672
    networks:
      - pulse_network

networks:
  pulse_network:
    driver: bridge
