name: Python
on: [push, pull_request]
jobs:
  Pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest pytest-cov
          pip install -e .
      - name: Test with pytest
        run: |
          pytest --junitxml=pytest.xml --cov-report "xml:coverage.xml" --cov=git_hg_sync tests/
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: coverage.xml
          title: Coverage
          badge-title: Coverage
          junitxml-path: pytest.xml
          junitxml-title: JUnit Xml Summary
